---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & test
  image: plugins/docker
  environment:
    GH_PAT:
      from_secret: github_private_org_access
  settings:
    target: TESTS
    build_args:
    - GITHUB_USER=dgrechka
    - GITHUB_PAT=$${GH_PAT}
- name: build & push docker image
  image: plugins/docker
  when:
    branch:
    - main    
  environment:
    GH_PAT:
      from_secret: github_private_org_access
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: lostpetinitiative/calvin_zhirui_yolo5_head_detector
    target: FINAL
    auto_tag: true
    force_tag: true
    build_args:
    - GITHUB_USER=dgrechka
    - GITHUB_PAT=$${GH_PAT}