---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & test docker image
  image: plugins/docker
  when:
    branch:
      exclude:
      - main
  environment:
    GITHUB_PAT:
      from_secret: github_private_org_access
  settings:
    dry_run: true
    target: TESTS
    build_args_from_env:
    - GITHUB_PAT
    build_args:
    - GITHUB_USER=dgrechka    
- name: buildm test & push docker image
  image: plugins/docker
  when:
    branch:
    - main    
  environment:
    GITHUB_PAT:
      from_secret: github_private_org_access
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: lostpetinitiative/calvin_zhirui_yolo5_head_detector
    target: FINAL
    auto_tag: true
    force_tag: true
    build_args_from_env:
    - GITHUB_PAT    
    build_args:
    - GITHUB_USER=dgrechka